services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p13-crossloco-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: p13-crossloco-frontend
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend
    restart: always
